# Form implementation generated from reading ui file 'ui/manager.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 430)
        MainWindow.setMinimumSize(QtCore.QSize(600, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.servicesColumn = QtWidgets.QTableView(parent=self.centralwidget)
        self.servicesColumn.setMinimumSize(QtCore.QSize(100, 0))
        self.servicesColumn.setObjectName("servicesColumn")
        self.horizontalLayout.addWidget(self.servicesColumn)
        self.accountsColumn = QtWidgets.QTableView(parent=self.centralwidget)
        self.accountsColumn.setMinimumSize(QtCore.QSize(200, 0))
        self.accountsColumn.setObjectName("accountsColumn")
        self.horizontalLayout.addWidget(self.accountsColumn)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        self.menuUser = QtWidgets.QMenu(parent=self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newServiceAction = QtGui.QAction(parent=MainWindow)
        self.newServiceAction.setShortcut("")
        self.newServiceAction.setObjectName("newServiceAction")
        self.newAcoountAction = QtGui.QAction(parent=MainWindow)
        self.newAcoountAction.setObjectName("newAcoountAction")
        self.settingsAction = QtGui.QAction(parent=MainWindow)
        self.settingsAction.setObjectName("settingsAction")
        self.logoutAction = QtGui.QAction(parent=MainWindow)
        self.logoutAction.setObjectName("logoutAction")
        self.editAction = QtGui.QAction(parent=MainWindow)
        self.editAction.setShortcut("")
        self.editAction.setShortcutVisibleInContextMenu(True)
        self.editAction.setObjectName("editAction")
        self.deleteAction = QtGui.QAction(parent=MainWindow)
        self.deleteAction.setObjectName("deleteAction")
        self.menuUser.addAction(self.logoutAction)
        self.menuFile.addAction(self.newServiceAction)
        self.menuFile.addAction(self.newAcoountAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.editAction)
        self.menuFile.addAction(self.deleteAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Another password manager"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.newServiceAction.setText(_translate("MainWindow", "New service"))
        self.newAcoountAction.setText(_translate("MainWindow", "New account"))
        self.settingsAction.setText(_translate("MainWindow", "Settings"))
        self.logoutAction.setText(_translate("MainWindow", "Log out"))
        self.editAction.setText(_translate("MainWindow", "Edit"))
        self.editAction.setToolTip(_translate("MainWindow", "Edit"))
        self.deleteAction.setText(_translate("MainWindow", "Delete"))
